spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study_oauth2?serverTimezone=Asia/Seoul
    username: study_oauth2
    password: study_oauth2
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

app:
  auth:
    tokenSecret: { token_secret }
    tokenExpiration: 864000000
  cors:
    allowedOrigins: http://localhost:3000
    maxAge: 3600
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect